version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=campus-compass
      - MONGO_INITDB_ROOT_PASSWORD=campus-compass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=campus-compass
      - ME_CONFIG_MONGODB_ADMINPASSWORD=campus-compass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"